src/content/index.tsx
src/content/utils.ts

All buttons are gone, fix selectors

Fix broken CSS Selectors 

---

src/content/index.tsx

Fixed duplicate button bug

---

src/content/utils.ts

See: https://github.com/mlool/workday-calendar-extension/issues/16

Bug fix: support 24-hour time

---

src/content/App/App.tsx

Hopefully fixes the storage quota bug and lets the storage preserve people's schedules

Fixed react hook loop

---

src/content/App/App.tsx
src/content/Icons/ExportIcon.tsx
src/content/TopBar/TopBar.tsx

**Add Import JSON File Functionality**
- Implemented a download button to export `sections` data as a JSON file

Export Button added

---

src/content/Calendar/utils.ts
src/content/SectionPopup/GradesComponent/GradesComponent.css
src/content/SectionPopup/GradesComponent/GradesComponent.tsx
src/content/SectionPopup/GradesComponent/GradesHelper.ts
src/content/SectionPopup/SectionPopup.css
src/content/SectionPopup/SectionPopup.tsx

Addresses #33 
Added grades information to the popup.
Will call the UBC grades api and display average infromation.
Also will form a link to UBC grades.
Make sure to test both UBC Vancouver and UBC O campus courses, as they have are under a different URI.
Some courses throw 404, Some I have confirmed are not on the UBC grades website.

Add UBC Grades Integration

---

src/content/App/App.types.ts
src/content/SectionPopup/SectionPopup.css
src/content/SectionPopup/SectionPopup.tsx
src/content/utils.ts

Duplicate of #60 
Had issues with my fork and had to start clean and that branch got deleted
Fixes issues mentioned in #60 and implements feedback regarding multiple professor support

Instructors in Section Popup

---

src/content/utils.ts

Fix for #58 
Should also address #59 
Fixes issue where courses like DES_V 201 that contained a ' -  ' could not be added

Fix issue where could not add courses where the title contained a ' - '

---

src/content/Form/Form.css
src/content/Form/Form.tsx
src/content/Settings/Settings.css

Made the Export Calendar button a bit more consistent w/ the Discord button and made the New Course Info text a bit more noticeable/easier to read.

Slightly improve UI

---

src/content/App/App.tsx
src/content/Settings/Settings.tsx

I haven't edited the CSS on it, i have to do lab due tonight sorry :(

Implemented Import button

---

src/content/index.tsx

Fixes the issue of adding buttons when the user is on the "Find Course Sections for Saved Schedule" page. 
resolves #63

Fix two buttons in saved schedule

---

src/content/Settings/ExportImport/ExportImport.css
src/content/Settings/ExportImport/ExportImport.tsx
src/content/Settings/ExportImport/ExternalCalendarExport.tsx
src/content/Settings/ExportImport/ExternalCalendarExportHelper.tsx

Refactored to its own component
Added UI to export only specific worklist
When user clicks to export, they are given option to choose, after they choose, UI goes back to original

Improvements to External Calendar Export

---

src/content/utils.ts

Revert to previous method of parsing instructors due to workday changes

Fix instructor parsing

---

src/content/Settings/Tools/Tools.tsx

Hide tools as coming Soon
@mlool

hide tools as coming soon

---

src/content/App/App.types.ts
src/content/SectionPopup/SectionPopup.css
src/content/SectionPopup/SectionPopup.tsx
src/content/utils.ts

- Adds "courseID" field to section data
- Displays link to workday course page when clicking popup title 
https://github.com/mlool/workday-calendar-extension/assets/60302907/74cd9de9-222f-4151-baf6-9983343059db

add course links to popup

---

src/content/utils.ts

instructor selection does not need to access parent element as information is available in element itself. Fixes workday adding "data-automation-id=promptOption" elsewhere on page
@mlool

Fix instructors (again)

---

public/manifest.json
src/background/index.ts
src/content/utils.ts

- Infrastructure for intercepting calls and adding cookie header before letting call continue
- Refactors courseId fetching to use API calls instead of extracting from the DOM
- ran prettier on util.ts
-  Added 2 utility functions:
- findCourseId(name: string) - returns a course ID (also available in section data but incase needs to be regenerated or if not available
- isCourseFormatted(courseName: string) returns true if course Name is formatted correctly for use in search query

Refactor Course ID Fetching, Infrastructure To Make Workday Calls

---

src/content/ConfirmationModal/ConfirmationModal.css
src/content/InfoModal/InfoModal.css
src/content/Settings/ExportImport/ExportImport.tsx
src/content/Settings/ExportImport/ExportImportIndividual/ExportImportIndividual.tsx
src/content/utils.ts

Allows for loading in the id when importing worklists (so that we can back fill ids for those who don't have it already)

updated import export checks

---

src/content/index.tsx
src/content/utils.ts

https://github.com/mlool/workday-calendar-extension/assets/60302907/e53312a8-82fe-4435-996e-56e5cc7dadca
User does need to click add section for the last section at the end. Should be fine, acts as a "confirmation" ig
User needs to keep the target worklist open in extension before running. Will not overwrite any existing classes
Sorry for large file diff, index was getting messy, ran prettier on it

Saved Schedules -> Worklists Sync

---

src/content/utils.ts

Fix issue where 2 term courses does not render

Fix Two Term Courses

---

public/manifest.json
src/background/index.ts

Updated manifest to use correct permissions to avoid errors
@jaskirat-gill

Updated Manifest

---

public/manifest.json
src/background/index.ts
src/content/index.tsx
src/content/utils.ts

Fix Header Interception/Modification (Again) & Bug Fixes

---

src/content/App/App.tsx

Fixed sync data (from 1.4 and below) disappearing on auto update

Fixed sync data (from 1.4 and below) disappearing on auto update

---

.gitattributes

- Prevents Prettier from losing it over line endings on Windows

chore: prevent git from converting LF to CRLF

---

public/manifest.json
src/background/index.ts
src/content/App/App.tsx
src/content/ModalLayer.tsx
src/content/Settings/ExportImport/ExportImport.tsx
src/content/index.tsx
src/content/utils.ts

fix: dynamically update contextID on page changes

---

src/content/App/App.types.ts
src/content/SectionPopup/InstructorComponent/InstructorComponent.tsx
src/content/SectionPopup/LocationsComponent/LocationComponent.tsx
src/content/SectionPopup/SectionInfoBody.tsx
src/content/Settings/ExportImport/ExportImportIndividual/ExportImportIndividual.tsx
src/content/utils.ts

Revert Live Loading Supplementary Data

---

src/content/index.tsx
src/content/utils.ts

Very small fix for API, original fix for -off-by-one context ID error I forgot that javascript treats ``undefined`` as falsey and thus my recursive check made it so the fix didnt do anything
@mlool

fix off-by-one API Error

---

src/content/index.tsx

- fixes bug where workday login/logout on firefox would show a blank screen instead of the login/logout page
- fixes bug where autofill could not detect popup on firefox
No visual changes.
@mlool

fix: unblocked login/logout and enabled autofill on firefox

---

src/content/index.tsx
src/content/utils.ts

- Adds compatibility with [JustintyC's workday reskin extension](https://github.com/JustintyC/Custom-Workday-Courselist-Extension)
No visual changes on our side, but here's how it looks like on the reskin extension:
https://github.com/mlool/workday-calendar-extension/assets/72814106/ea4ff55c-1c8b-4749-9cb9-3ce171b54d5a
@mlool

feat: add compatibility with JustintyC reskin extension

---

src/content/index.tsx

Styling & DOM changes for compatibility with [my extension](https://github.com/JustintyC/Custom-Workday-Courselist-Extension)
@mlool

button insertion position + styling

---

src/backends/scheduler/nameSearchApi.ts
src/backends/scheduler/nameSearchHelpers.ts
src/backends/workday/idSearchApi.ts
src/content/Form/Form.tsx
src/content/index.tsx
src/content/utils.ts

Places a loading placeholder and progress bar where the course code and title are placed while course is being fetched
https://github.com/mlool/workday-calendar-extension/assets/60302907/a377da16-d24a-4c02-8f62-d3b64f55b432

Feat: Add course adding "Loading" text and progress bar 

---

src/content/ModalLayer.tsx
src/content/ProgressBar/ProgressBar.css
src/content/ProgressBar/ProgressBar.tsx
src/content/Settings/ExportImport/ExportImport.tsx
src/content/Settings/ExportImport/ExportImportIndividual/ExportImportIndividual.tsx
src/content/Settings/ExportImport/ExportImportPopups/ExportCalendarPopup.tsx

https://github.com/mlool/workday-calendar-extension/assets/60302907/6178b5a7-d7fa-4c9d-93ef-f1c85a8f850d

Feat: Add loading progress bar to imports

---

firefox-manifest.json
public/manifest.json
src/backends/rateMyProf.ts
src/background/index.ts
src/components/ColoredRangeDetail.css
src/components/ColoredRangeDetail.tsx
src/content/SectionPopup/GradesComponent/GradesComponent.tsx
src/content/SectionPopup/InstructorComponent/InstructorComponent.tsx
src/content/SectionPopup/SectionInfoBody.tsx
src/content/utils.ts
src/index.css

- Shows RateMyProf ratings next to prof names in section info popup
- Resolves #109 
https://github.com/mlool/workday-calendar-extension/assets/72814106/85f1e5b6-7f37-468e-84f4-f6cce506ca07
@mlool

feat: ratemyprof integration

---

firefox-manifest.json
public/manifest.json
src/components/TabBar.css
src/components/TabBar.tsx
src/content/Calendar/Calendar.tsx
src/content/Calendar/calendarHelpers.ts
src/content/CalendarContainer/CalendarContainer.tsx
src/content/Form/Form.css
src/content/Settings/ExportImport/ExportImport.tsx
src/index.css

1. Styling change
2. Fixed 2 term conflict bug
3. Fixed import doesn't fully fetch data

Fix two term bug and styling changes

---

src/content/SectionPopup/SectionInfoBody.tsx

Fix: Term 2 Duplicate Locations

---

src/components/TabBar.tsx
src/content/CalendarContainer/CalendarContainer.tsx

fix: incorrect prop on TabBar

---

src/content/Settings/ExportImport/ExportImport.tsx

fixed minor import bug

---

public/manifest.json
src/content/Calendar/Calendar.css
src/content/CalendarContainer/CalendarContainer.css
src/content/Form/Form.css
src/content/ModalLayer.css
src/content/ProgressBar/ProgressBar.css
src/content/Settings/ExportImport/ExportImportPopups/ExportImportPopup.css
src/content/Settings/Settings.css
src/content/Settings/Settings.tsx
src/content/TopBar/TopBar.css
src/content/index.tsx

#163 
There have been reports of smaller screens having issues, since we set a fixed pixel height.
https://github.com/mlool/workday-calendar-extension/assets/89222842/a1f2a3e5-34b0-4c15-a3b1-de58f9e40b5b
@mlool 
Lets test with some laptop screens.  13 inch if possible.
I checked on 1080p & 1440p with 27inch screen, and my 15inch laptop with 1920x1200

Refactor to remove Fixed Pixel Height

---

src/content/Settings/ExportImport/ExportImport.tsx

Small fix for progress bars starting at 100% for post 1.5 worklist importing

feat: Improve progress handling

---

src/backends/scheduler/nameSearchApi.ts
src/backends/workday/idSearchApi.ts
src/content/utils.ts

1. Adding ability to scrape courseID from DOM
2. Priority of fetching data changed to CourseId from DOM > CourseId from scheduler > Manual Entry
3. Fetch times significantly approved by ~2x (~700ms to ~350ms) on average
No visual changes

refactor: Update course fetching to prefer extracting course ID from DOM

---

src/backends/scheduler/nameSearchHelpers.ts
src/domManipulators/copySchedules.ts

implement progress tracking for saved schedules and registered

---

src/content/App/App.tsx
src/content/Icons/ExternalLinkIcon.tsx
src/content/TopBar/TopBar.tsx

Add link to ubc student hub

---

src/content/index.tsx

Workday DOM Changes Patch

---

src/content/App/App.tsx

Add check preventing users from importing multiple worklists into one
